### ISSUE TITLE
ESPCN's architecture 

### ISSUE THREAD

**Issue by kligvasser** [leftthomas/SuperResolution#1]
The suggested model is a bit different than the on in the paper. You got 4 convolutional layers, whereas, there are only 3 in the paper. Have you tried less? Why do you have sigmoid in the output layer?
Thank you very much!
Idan

**Comment by leftthomas** [comment]
@kligvasser , you could change that model, it's easy, I use sigmoid to make sure the output image value is between [0,1], you also could use tanh to the last layer, and add 1 then div it by 2 to make sure it between [0,1].
