### ISSUE TITLE
what are the license terms for pixelsuffle()?

### ISSUE THREAD

**Issue by supersonicai** [leftthomas/SuperResolution#10]
hi,

what are the license terms for pixelsuffle()?
can i apply espcn(w/ torch.nn.module.pixelsuffle) to my service for the commercial use?
Thanks

**Comment by leftthomas** [comment]
@supersonicai yes, you can

**Comment by supersonicai** [comment]
really? i believe that there is a patent related to this module.
- https://patents.google.com/patent/US20170347060A1/en

I was told that the body of pixelshuffle() is just implementation of the espcn paper protected by the US20170347060A1 patent.
are you sure that i could use it for commercial use without any restrictions?

**Comment by leftthomas** [comment]
@supersonicai I just use it with PyTorch API, so if PyTorch say yes, then I think it is ok

**Comment by suke27** [comment]
> 

you can replace it with deconv and finetune, then you can use it for commercial
