### ISSUE TITLE
Could re-release training data or pre-train model again?

### ISSUE THREAD

**Issue by intere2960** [leftthomas/SuperResolution#12]
As the title, all baidu yun url are missing, and I try to use pre-train model but have "UnpicklingError: invalid load key, '\xef'" problem when loading model. Could you release those data again? Or could you send those data to my email intere2960@yahoo.com.tw?

p.s. My platform is windows and use python 3.6.2 & pytorch 0.4.0. (windows don't have pytorch 0.3.1)

**Comment by leftthomas** [comment]
this code should be run on Ubuntu, windows load path will encounter error

**Comment by intere2960** [comment]
Unfortunately, I try another Ubuntu platform with python 3.6.8 & pytorch 0.3.1 still get "UnpicklingError: invalid load key, '\xef'". Could you help me to resolve my problem? I check all close issue on this respository but those solution can't work.

![1](https://user-images.githubusercontent.com/7983915/55633680-7b5cf280-57ef-11e9-8e5e-ccb174b596d0.PNG)
![2](https://user-images.githubusercontent.com/7983915/55633691-7ef07980-57ef-11e9-9aef-daf10c609801.PNG)

**Comment by leftthomas** [comment]
@intere2960 does these data links are missing? [Train](https://pan.baidu.com/s/1c17nfeo), [Test](https://pan.baidu.com/s/1nuGyn8l).
And because I haven't save the pre-train model, so if it has been damaged, you should train from scratch by yourself, sorry for that.

**Comment by intere2960** [comment]
It seems those link can't access it. (PC & Mobile) Or I have to use VPN to access China internet domain?

PC:
![image](https://user-images.githubusercontent.com/7983915/55667304-148e1680-588d-11e9-91c9-da6f3d51a414.png)

Mobile:
![Screenshot_20190406-165844](https://user-images.githubusercontent.com/7983915/55667335-89615080-588d-11e9-95b9-3bcbf3bbc39d.jpg)

**Comment by leftthomas** [comment]
@intere2960 look at [this repo](https://github.com/leftthomas/SRGAN). Are these links unavailable? The data is same with that repo, you could download from that repo.

**Comment by intere2960** [comment]
I get the same result as ESPCN. Can't access it.

**Comment by leftthomas** [comment]
@intere2960 I have updated these links

**Comment by intere2960** [comment]
I still can't access it, but I try VPN use japan, hong kong, US IP can access link. I don't know whether my IP address can't access baidu. (I'm in Taiwan)

**Comment by leftthomas** [comment]
@intere2960 I didn't know why, maybe Baidu restricts this service in some areas. Now these links in my repo are all right (I have tested), then if you can't access still, maybe you should change your IP address, or contact Baidu to ask help.
