### ISSUE TITLE
RuntimeError: cuda runtime error (8) : invalid device function

### ISSUE THREAD

**Issue by limusen123** [leftthomas/SuperResolution#17]
My CUDA is 10.0, Python is 3.6, GPU computing power is 5.0, tensorflow version is 1.14.0, running train.py is wrong.            Runtime Error: CUDA runtime error (8): invalid device function            Another thing I don't understand is, when I run train. py, what is the number of data I read in 261, and where does 261 come from? 0%| | 0/261 [00:00<?,? It/s]

**Comment by leftthomas** [comment]
@limusen123 
1. 261 is computed by `DataLoader` according to the `batch_size` and Len(dataset)
2. CUDA runtime error is caused by pertained model, you should load model to cpu and then convert it to cuda

**Comment by Risemxd** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'epochs/epoch_3_100.pt'
I couldn't find the epoch_3_100.pt file in the epochs folder. I would appreciate it if you help me to solve it.
