### ISSUE TITLE
[mpeg2video @ 0x355f2a20] MPEG1/2 does not support 15/1 fps Could not open codec 'mpeg2video': Unspecified error

### ISSUE THREAD

**Issue by why21** [leftthomas/SuperResolution#2]
Hello, when I ran: $python test_video.py, I got an error about video 爱情废柴.mp4

[mpeg2video @ 0x355f2a20] MPEG1/2 does not support 15/1 fps
Could not open codec 'mpeg2video': Unspecified error

The others were right, I don't know what's matter with this video, please help me, thanks!

**Comment by leftthomas** [comment]
@why21 you could change the codec in test_video.py, if it didn't work, maybe the video is broken, you could change another video to test the code.
