### ISSUE TITLE
作者你好，我有几个问题想向您请教一下

### ISSUE THREAD

**Issue by tzl1** [leftthomas/SuperResolution#21]
1、训练集数据必须要使用VOC2012数据集吗
2、假设我测试时用的是摄像头捕获的视频或者说只有720P的视频能够达到实时增强的效果吗

**Comment by leftthomas** [comment]
@tzl1 the answer of first one is no, you can change the data as you want;
the second one depends on you computer

**Comment by tzl1** [comment]
Thank you for your help
