### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'epochs/epoch_3_100.pt'

### ISSUE THREAD

**Issue by Risemxd** [leftthomas/SuperResolution#28]
When I ran test_image.py, an error occurred: FileNotFoundError: [Errno 2] No such file or directory: 'epochs/epoch_3_100.pt'.
Epoch_3_100.pt could not be found, please help to solve it, thank you very much.

**Comment by leftthomas** [comment]
@Risemxd 
Duplicate of #25
