### ISSUE TITLE
Discuss that the SISR recurring result is lower than the original paper?

### ISSUE THREAD

**Issue by FBLeee** [leftthomas/SuperResolution#33]
First of all ，thank you very much for your hard work to replicate the program！

The training set used in the original paper is 91 high-definition images, and the effect achieved by [×3_SR] is Set5—32.55dB. 

The training set you used is 16700 images, and the reproduced effect is Set5—31.51dB. Why is the effect worse when using a larger training set?

And I found that the highest value of your program is Set5-34.09dB is higher than the original paper, so I guess the original paper uses the highest value as the result?

**Comment by leftthomas** [comment]
@943301098 you could mail the author
