### ISSUE TITLE
关于train.py的问题

### ISSUE THREAD

**Issue by Meteors-flash** [leftthomas/SuperResolution#36]
在运行完python -m visdom server & python train.py后出来了visdom可视化界面，但是没有出现任何数据，只有顶部的导航栏和蓝底，没有train.py里写的向visdom界面生成训练进度等数据的可视化窗口，想问问作者这样的情况该怎么解决呢？感谢！

**Comment by leftthomas** [comment]
@Meteors-flash you need reference `visdom` api document
