### ISSUE TITLE
请求可下载路径

### ISSUE THREAD

**Issue by Vonuo** [leftthomas/SuperResolution#39]
哥们，
有能下载的训练数据集链接吗？
发我邮箱也行：fengqixin16@mails.ucas.ac.cn
万分感谢！膜拜！

**Comment by leftthomas** [comment]
@Vonuo `readme` has stated the download link.

**Comment by Vonuo** [comment]
> @Vonuo `readme` has stated the download link.

yesterday, i can access the link but can't download it, because it was removed
today, i can not even access the link

**Comment by leftthomas** [comment]
@Vonuo which link you can't access? I just check that all links can be access.

**Comment by Vonuo** [comment]
> @Vonuo which link you can't access? I just check that all links can be access.

"Train dataset has 16700 images and Val dataset has 425 images. Download the datasets from here(access code:5tzp), and then extract it into data directory. Finally run"
[here](https://pan.baidu.com/s/1xuFperu2WiYc5-_QXBemlA)

**Comment by leftthomas** [comment]
@Vonuo it's a Baidu Pan link, can be assessed, you just check it by yourself.

**Comment by Vonuo** [comment]
> @Vonuo it's a Baidu Pan link, can be assessed, you just check it by yourself.

ok, thanks.
