### ISSUE TITLE
[WinError 3] 系统找不到指定的路径。: 'data/test/SRF_3/data/'

### ISSUE THREAD

**Issue by MBCmbc** [leftthomas/SuperResolution#4]
[WinError 3] 系统找不到指定的路径。: 'data/test/SRF_3/data/'

**Comment by MBCmbc** [comment]
Where is the data？

**Comment by leftthomas** [comment]
@MBCmbc , the path is unix path, if you want to run on windows, you should change path by using '\\' to replace '/'
