### ISSUE TITLE
The transform of input: Gaussian kernel

### ISSUE THREAD

**Issue by zhangcheng-007** [leftthomas/SuperResolution#41]
The paper blurs HR using a Gaussian filter and sub-sample it. Is the Gaussian kernel implemented in the code? I just see bicubic.

**Comment by leftthomas** [comment]
@zhangcheng-007 you could implement them by yourself.

**Comment by zhangcheng-007** [comment]
I have just entered this field. I cancelled the annotation, and the effect is not very good. Source code of SRCNN uses bicubic interpolation to generate LR image, similar to your method.
