### ISSUE TITLE
UnpicklingError: invalid load key, '\xef'

### ISSUE THREAD

**Issue by Kiris-Wu** [leftthomas/SuperResolution#6]
Hi ! When I run the test_image.py to load the given model I met the error:_pickle.UnpicklingError: invalid load key, '\xef'. I tried https://github.com/CSAILVision/places365/issues/25 and set the encoding to be utf-8 or unicode but it doesn't work. I hope anyone could give me any advice? Thanks in advance!

**Comment by leftthomas** [comment]
@Kiris-Wu firstly, what device the model loaded? CPU or GPU? What's the parameters you pass to `test_image.py`?

**Comment by Kiris-Wu** [comment]
Sorry for the late reply. I didn't receive the notice.
I load the model in CPU and modify the code as:
model.load_state_dict(torch.load('epochs/' + MODEL_NAME,map_location=lambda storage, loc: storage)) 
The parameter I use is the default one for upscale=3 and the corresponding model.
@leftthomas Could I ask the specific version for the environment? I use 0.4.0 torch and 3.6 python.
Thanks again!

**Comment by leftthomas** [comment]
The code only works for PyTorch 0.3.1

**Comment by Kiris-Wu** [comment]
Unfortunately, after change my PyTorch to 0.3.1, the error still exists. I have download the epoch model again but doesn't work. Since I'm using Win, should I set any encoding to load the file? Or does pickle's version affect loading? I use 4.0 version of pickle.

**Comment by leftthomas** [comment]
@Kiris-Wu #4

**Comment by Catniiip** [comment]
I'm facing the same problem now, so how to make it work?
I load the model in CPU, too. And the upscale factor I set is 2.

**Comment by leftthomas** [comment]
@Catniiip , if you load with CPU, you should change code with https://github.com/leftthomas/ESPCN/blob/1de18099beb28dad8aebad17f8238c90734b2fba/test_video.py#L35

**Comment by Catniiip** [comment]
Thanks for your reply but it still returns:

`Traceback (most recent call last):
  File "test_image.py", line 29, in <module>
    model.load_state_dict(torch.load('epochs/' + MODEL_NAME, map_location=lambda storage, loc: storage))
  File "/Users/yidan/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/Users/yidan/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 459, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\xef'.`

is there any other ways to fix this?

**Comment by leftthomas** [comment]
@Catniiip , if it still not work, I'm afraid maybe the pre-trained weight file have been damaged,  then  you should train the model from scratch.

**Comment by Congying-Wang** [comment]
> Hi ! When I run the test_image.py to load the given model I met the error:_pickle.UnpicklingError: invalid load key, '\xef'. I tried [CSAILVision/places365#25](https://github.com/CSAILVision/places365/issues/25) and set the encoding to be utf-8 or unicode but it doesn't work. I hope anyone could give me any advice? Thanks in advance!

Hi!  I am facing the same problem? Have you solved it?

**Comment by Catniiip** [comment]
Sorry……
I haven’t solved this problem😂
Can you inform me if you find any way to solve it? Many thanks 🙏

发自我的 iPhone

在 2018年10月11日，14:31，Congying-Wang <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi ! When I run the test_image.py to load the given model I met the error:_pickle.UnpicklingError: invalid load key, '\xef'. I tried CSAILVision/places365#25<https://github.com/CSAILVision/places365/issues/25> and set the encoding to be utf-8 or unicode but it doesn't work. I hope anyone could give me any advice? Thanks in advance!

Hi! I am facing the same problem? Have you solved it?

**Comment by aiXia121** [comment]
have the same problem? Please reload the code and model's weight. THX @leftthomas

**Comment by jilner** [comment]
> have the same problem? Please reload the code and model's weight. THX @leftthomas

hello  ,did you reslove this problem?

**Comment by zhenhuahu** [comment]
Met the same problem. Has anyone solved it? Thanks

**Comment by casivido** [comment]
@leftthomas It doesn't seem like this has been solved, as I am also running into this. Why did you close this with so many people still having the issue?

**Comment by leftthomas** [comment]
@casivido If the file is damaged, you should train the model by yourself, the code is written one years ago, now I'm not focus on this area, so I have no plan to re-train the model and update the pre-trained model files.

**Comment by he-y** [comment]
See this :https://github.com/CSAILVision/places365/issues/25#issuecomment-333871990

**Comment by AidanP24** [comment]
[SOLVED]
Hey guys, 

I just had this issue as well. I solved it by rebuilding the file that was causing the corruption. 

I would recommend you do the same (likely by deleting it and creating it again).

I hope this is a definitive answer for someone.

**Comment by datascientist9000** [comment]
> [SOLVED] Hey guys,
> 
> I just had this issue as well. I solved it by rebuilding the file that was causing the corruption.
> 
> I would recommend you do the same (likely by deleting it and creating it again).
> 
> I hope this is a definitive answer for someone.

how can i create it again if i dont have main source
