### ISSUE TITLE
为什么我的浏览器无法访问http://localhost:8097，提示This site can’t be reached。localhost refused to connect.您知道怎么解决吗？谢谢

### ISSUE THREAD

**Issue by Xiaonanzhu123** [leftthomas/SuperResolution#9]
Why can't my Google Chrome access this URL?
It prompts：This site can’t be reached。localhost refused to connect.
what can i do   thank you

**Comment by leftthomas** [comment]
@Xiaonanzhu123  检查一下端口是不是被占用了
